// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example.inputs;

    public class FooArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<Boolean> a = java.util.Optional.empty();
        public Boolean getA() {
           return a.isPresent() ? a.get() : null;
        }
        public FooArgs setA(Boolean a) {
            this.a = a != null ? java.util.Optional.of(a) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Boolean> b = java.util.Optional.empty();
        public Boolean getB() {
           return b.isPresent() ? b.get() : null;
        }
        public FooArgs setB(Boolean b) {
            this.b = b != null ? java.util.Optional.of(b) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<Integer> c = java.util.Optional.empty();
        public Integer getC() {
           return c.isPresent() ? c.get() : null;
        }
        public FooArgs setC(Integer c) {
            this.c = c != null ? java.util.Optional.of(c) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Integer> d = java.util.Optional.empty();
        public Integer getD() {
           return d.isPresent() ? d.get() : null;
        }
        public FooArgs setD(Integer d) {
            this.d = d != null ? java.util.Optional.of(d) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<String> e = java.util.Optional.empty();
        public String getE() {
           return e.isPresent() ? e.get() : null;
        }
        public FooArgs setE(String e) {
            this.e = e != null ? java.util.Optional.of(e) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> f = java.util.Optional.empty();
        public String getF() {
           return f.isPresent() ? f.get() : null;
        }
        public FooArgs setF(String f) {
            this.f = f != null ? java.util.Optional.of(f) : java.util.Optional.empty();
            return this;
        }

        public FooArgs(
            Boolean a,
            Integer c,
            String e
            ) {
        this.a = java.util.Optional.of(a);
        this.c = java.util.Optional.of(c);
        this.e = java.util.Optional.of(e);
    }
}
