// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;
    public enum Diameter {
        Sixinch(6),
        Twelveinch(12);
        public final Double label;

        private Diameter(Double label) {
            this.label = label;
        }
    }
