// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;

    public class NurseryArgs extends io.pulumi.ResourceArgs {

        /**
        * The sizes of trees available
        */
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.Map<String, io.pulumi.plant.tree.v1.TreeSize>> sizes = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.plant.tree.v1.TreeSize> getSizes() {
           return sizes.isPresent() ? sizes.get() : null;
        }
        public NurseryArgs setSizes(java.util.Map<String, io.pulumi.plant.tree.v1.TreeSize> sizes) {
            this.sizes = sizes != null ? java.util.Optional.of(sizes) : java.util.Optional.empty();
            return this;
        }


        /**
        * The varieties available
        */
        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<java.util.List<io.pulumi.plant.tree.v1.RubberTreeVariety>> varieties = java.util.Optional.empty();
        public java.util.List<io.pulumi.plant.tree.v1.RubberTreeVariety> getVarieties() {
           return varieties.isPresent() ? varieties.get() : null;
        }
        public NurseryArgs setVarieties(java.util.List<io.pulumi.plant.tree.v1.RubberTreeVariety> varieties) {
            this.varieties = varieties != null ? java.util.Optional.of(varieties) : java.util.Optional.empty();
            return this;
        }

        public NurseryArgs(
            java.util.List<io.pulumi.plant.tree.v1.RubberTreeVariety> varieties
            ) {
        this.varieties = java.util.Optional.of(varieties);
    }
}
