// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;
public class Nursery extends io.pulumi.CustomResource {
    /**    * Create a Nursery resource with the given name, arguments, and options.
    * @param name the unique name of the resource
    * @param args The arguments used to populate this resource's properties
    * @param options A bag of options that control this resource's behavior
    */
    public Nursery(String name, NurseryArgs args, @javax.annotation.Nullable io.pulumi.CustomResourceOptions options) {
        super("plant:tree/v1:Nursery", name, args, makeResourceOptions(options, io.pulumi.Input.create("")));
    }

    private Nursery(String name, io.pulumi.Input<String> id, @javax.annotation.Nullable io.pulumi.CustomResourceOptions options) {
        super("plant:tree/v1:Nursery", name, null, makeResourceOptions(options, id));
    }

    private static io.pulumi.CustomResourceOptions makeResourceOptions(@javax.annotation.Nullable io.pulumi.CustomResourceOptions options, io.pulumi.Input<String> id) {
        io.pulumi.CustomResourceOptions defaultOptions = new io.pulumi.CustomResourceOptions();
        defaultOptions.Version = Utilities.Version;
        io.pulumi.CustomResourceOptions merged = io.pulumi.CustomResourceOptions.merge(defaultOptions, options);
        merged.Id = id;
        return merged;
    }
    /**    * Get an existing Nursery resource's state with the given name, ID, and optional extra
    * properties used to qualify the lookup.
    * @param name The unique name of the resulting resource.
    * @param id The unique provider ID of the resource to lookup.
    * @param options A bag of options that control this resource's behavior.
    */
    public static Nursery get(String name, @javax.annotation.Nullable String id, io.pulumi.CustomResourceOptions options) {
        return new Nursery(name, io.pulumi.Input.create(id), options);
    }
}
