// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;

    public class RubberTreeState extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> farm = "(unknown)";
        public String getFarm() {
           return farm.isPresent() ? farm.get() : null;
        }
        public RubberTreeState setFarm(String farm) {
            this.farm = farm != null ? java.util.Optional.of(farm) : java.util.Optional.empty();
            return this;
        }

        public RubberTreeState(

            ) {
    }
}
