// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;

    public class RubberTreeArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.plant.inputs.ContainerArgs> container = java.util.Optional.empty();
        public io.pulumi.plant.inputs.ContainerArgs getContainer() {
           return container.isPresent() ? container.get() : null;
        }
        public RubberTreeArgs setContainer(io.pulumi.plant.inputs.ContainerArgs container) {
            this.container = container != null ? java.util.Optional.of(container) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<io.pulumi.plant.tree.v1.Diameter> diameter = 6;
        public io.pulumi.plant.tree.v1.Diameter getDiameter() {
           return diameter.isPresent() ? diameter.get() : null;
        }
        public RubberTreeArgs setDiameter(io.pulumi.plant.tree.v1.Diameter diameter) {
            this.diameter = diameter != null ? java.util.Optional.of(diameter) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> farm = "(unknown)";
        public String getFarm() {
           return farm.isPresent() ? farm.get() : null;
        }
        public RubberTreeArgs setFarm(String farm) {
            this.farm = farm != null ? java.util.Optional.of(farm) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.plant.tree.v1.TreeSize> size = "medium";
        public io.pulumi.plant.tree.v1.TreeSize getSize() {
           return size.isPresent() ? size.get() : null;
        }
        public RubberTreeArgs setSize(io.pulumi.plant.tree.v1.TreeSize size) {
            this.size = size != null ? java.util.Optional.of(size) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<io.pulumi.plant.tree.v1.RubberTreeVariety> type = "Burgundy";
        public io.pulumi.plant.tree.v1.RubberTreeVariety getType() {
           return type.isPresent() ? type.get() : null;
        }
        public RubberTreeArgs setType(io.pulumi.plant.tree.v1.RubberTreeVariety type) {
            this.type = type != null ? java.util.Optional.of(type) : java.util.Optional.empty();
            return this;
        }

        public RubberTreeArgs(
            io.pulumi.plant.tree.v1.Diameter diameter,
            io.pulumi.plant.tree.v1.RubberTreeVariety type
            ) {
        this.diameter = java.util.Optional.of(diameter);
        this.type = java.util.Optional.of(type);
    }
}
