// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.tree.v1;
    /**
    * types of rubber trees
    */
    public enum RubberTreeVariety {
        Burgundy("Burgundy"),
        Ruby("Ruby"),
        Tineke("Tineke");
        public final String label;

        private RubberTreeVariety(String label) {
            this.label = label;
        }
    }
