// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant;
    /**
    * plant container sizes
    */
    public enum ContainerSize {
        FourInch(4),
        SixInch(6),
        EightInch(8);
        public final Integer label;

        private ContainerSize(Integer label) {
            this.label = label;
        }
    }
