// *** WARNING: this file was generated. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
package io.pulumi.plant;

class Utilities {
	static String Version = formatVersion(Utilities.class.getResourceAsStream("/version.txt").toString());

	private static String formatVersion(String versionString) {
		String trimmed = versionString.trim();
		String[] parts = trimmed.split("\n");
		if (parts.length== 2) {
			return parts[1].trim();
		} else {
			return trimmed;
		}

	}
}