// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.plant.outputs;

    public class Container extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.plant.ContainerBrightness> brightness = 1;
        public io.pulumi.plant.ContainerBrightness getBrightness() {
           return brightness.isPresent() ? brightness.get() : null;
        }
        public Container setBrightness(io.pulumi.plant.ContainerBrightness brightness) {
            this.brightness = brightness != null ? java.util.Optional.of(brightness) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> color = java.util.Optional.empty();
        public String getColor() {
           return color.isPresent() ? color.get() : null;
        }
        public Container setColor(String color) {
            this.color = color != null ? java.util.Optional.of(color) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> material = java.util.Optional.empty();
        public String getMaterial() {
           return material.isPresent() ? material.get() : null;
        }
        public Container setMaterial(String material) {
            this.material = material != null ? java.util.Optional.of(material) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<io.pulumi.plant.ContainerSize> size = java.util.Optional.empty();
        public io.pulumi.plant.ContainerSize getSize() {
           return size.isPresent() ? size.get() : null;
        }
        public Container setSize(io.pulumi.plant.ContainerSize size) {
            this.size = size != null ? java.util.Optional.of(size) : java.util.Optional.empty();
            return this;
        }

        public Container(
            io.pulumi.plant.ContainerSize size
            ) {
        this.size = java.util.Optional.of(size);
    }
}
