// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant;
    public enum ContainerBrightness {
        ZeroPointOne(0.1),
        One(1);
        public final double label;

        private ContainerBrightness(double label) {
            this.label = label;
        }
    }
