// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant;
    /**
    * plant container colors
    */
    public enum ContainerColor {
        Red("red"),
        Blue("blue"),
        Yellow("yellow");
        public final String label;

        private ContainerColor(String label) {
            this.label = label;
        }
    }
