// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant;
    public class Provider extends Pulumi.ProviderResource {
        /**        * Create a Provider resource with the given name, arguments, and options.
        * @param name the unique name of the resource
        * @param args The arguments used to populate this resource's properties
        * @param options A bag of options that control this resource's behavior
        */
        public Provider(string name, Optional<ProviderArgs> args, Optional<CustomResourceOptions> options) {
            super("plant", name, args.isPresent()?args.get(): new ProviderArgs(), makeResourceOptions(options, ""));
        }

        private static CustomResourceOptions makeResourceOptions(CustomResourceOptions options, Optional<Input<String>> id) {
            CustomResourceOptions defaultOptions = new CustomResourceOptions();
            defaultOptions.Verion = Utilities.Version;
            CustomResourceOptions merged = CustomResourceOptions.merge(defaultOptions, options);
            merged.Id = id.isPresent() ? id.get() : merged.Id;
            return merged;
        }
    }

    public final class ProviderArgs extends io.pulumi.ResourceArgs {
        public ProviderArgs(

            ) {
        }
        }
