// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant.Tree.V1;
    public enum Diameter {
        Sixinch(6),
        Twelveinch(12);
        public final double label;

        private Diameter(double label) {
            this.label = label;
        }
    }
