// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant.Tree.V1;
    public enum Farm {
        Pulumi_Planters_Inc_("Pulumi Planters Inc."),
        Plants_R_Us("Plants'R'Us");
        public final String label;

        private Farm(String label) {
            this.label = label;
        }
    }
