// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant.Tree.V1;
    public enum TreeSize {
        Small("small"),
        Medium("medium"),
        Large("large");
        public final String label;

        private TreeSize(String label) {
            this.label = label;
        }
    }
