// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.Plant;

    public final class Container {
        public final Optional<io.pulumiPlant.ContainerBrightness> brightness;
        public final Optional<String> color;
        public final Optional<String> material;
        public final io.pulumiPlant.ContainerSize size;

        private Container(
            Optional<io.pulumiPlant.ContainerBrightness> brightness,

            Optional<String> color,

            Optional<String> material,

            io.pulumiPlant.ContainerSize size
        ) {
            this.brightness = brightness;
            this.color = color;
            this.material = material;
            this.size = size;
        }
    }
