// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example.inputs;

    public class ArgFunctionArgs extends io.pulumi.InvokeArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.example.Resource> arg1 = java.util.Optional.empty();
        public io.pulumi.example.Resource getArg1() {
           return arg1.isPresent() ? arg1.get() : null;
        }
        public ArgFunctionArgs setArg1(io.pulumi.example.Resource arg1) {
            this.arg1 = arg1 != null ? java.util.Optional.of(arg1) : java.util.Optional.empty();
            return this;
        }

        public ArgFunctionArgs(

            ) {
    }
}
