// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example.outputs;

public final class ArgFunctionResult {
    public final io.pulumi.example.Resource result;

    private ArgFunctionResult(io.pulumi.example.Resource result
    ) {
        this.result = result;
    }
}
