// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;
public class OtherResource extends io.pulumi.ComponentResource {
    public io.pulumi.Output<java.util.Optional<io.pulumi.example.Resource>> foo;

    /**    * Create a OtherResource resource with the given name, arguments, and options.
    * @param name the unique name of the resource
    * @param args The arguments used to populate this resource's properties
    * @param options A bag of options that control this resource's behavior
    */
    public OtherResource(String name, OtherResourceArgs args, @javax.annotation.Nullable io.pulumi.ComponentResourceOptions options) {
        super("example::OtherResource", name, args != null ? args : new OtherResourceArgs(), makeResourceOptions(options, io.pulumi.Input.create("")), true);
    }

    private static io.pulumi.ComponentResourceOptions makeResourceOptions(@javax.annotation.Nullable io.pulumi.ComponentResourceOptions options, io.pulumi.Input<String> id) {
        io.pulumi.ComponentResourceOptions defaultOptions = new io.pulumi.ComponentResourceOptions();
        defaultOptions.Version = Utilities.Version;
        io.pulumi.ComponentResourceOptions merged = io.pulumi.ComponentResourceOptions.merge(defaultOptions, options);
        merged.Id = id;
        return merged;
    }
}
