// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class OtherResourceArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.example.Resource> foo = java.util.Optional.empty();
        public io.pulumi.example.Resource getFoo() {
           return foo.isPresent() ? foo.get() : null;
        }
        public OtherResourceArgs setFoo(io.pulumi.example.Resource foo) {
            this.foo = foo != null ? java.util.Optional.of(foo) : java.util.Optional.empty();
            return this;
        }

        public OtherResourceArgs(

            ) {
    }
}
