// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;
public class Resource extends io.pulumi.CustomResource {
    public io.pulumi.Output<java.util.Optional<String>> bar;

    /**    * Create a Resource resource with the given name, arguments, and options.
    * @param name the unique name of the resource
    * @param args The arguments used to populate this resource's properties
    * @param options A bag of options that control this resource's behavior
    */
    public Resource(String name, ResourceArgs args, @javax.annotation.Nullable io.pulumi.CustomResourceOptions options) {
        super("example::Resource", name, args != null ? args : new ResourceArgs(), makeResourceOptions(options, io.pulumi.Input.create("")));
    }

    private Resource(String name, io.pulumi.Input<String> id, @javax.annotation.Nullable io.pulumi.CustomResourceOptions options) {
        super("example::Resource", name, null, makeResourceOptions(options, id));
    }

    private static io.pulumi.CustomResourceOptions makeResourceOptions(@javax.annotation.Nullable io.pulumi.CustomResourceOptions options, io.pulumi.Input<String> id) {
        io.pulumi.CustomResourceOptions defaultOptions = new io.pulumi.CustomResourceOptions();
        defaultOptions.Version = Utilities.Version;
            defaultOptions.additionalSecretOutputs = com.google.common.collect.ImmutableList.of(
            "bar"
    );
        io.pulumi.CustomResourceOptions merged = io.pulumi.CustomResourceOptions.merge(defaultOptions, options);
        merged.Id = id;
        return merged;
    }
    /**    * Get an existing Resource resource's state with the given name, ID, and optional extra
    * properties used to qualify the lookup.
    * @param name The unique name of the resulting resource.
    * @param id The unique provider ID of the resource to lookup.
    * @param options A bag of options that control this resource's behavior.
    */
    public static Resource get(String name, @javax.annotation.Nullable String id, io.pulumi.CustomResourceOptions options) {
        return new Resource(name, io.pulumi.Input.create(id), options);
    }
}
