// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class ResourceArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> bar = java.util.Optional.empty();
        public String getBar() {
           return bar.isPresent() ? bar.get() : null;
        }
        public ResourceArgs setBar(String bar) {
            this.bar = bar != null ? java.util.Optional.of(bar) : java.util.Optional.empty();
            return this;
        }

        public ResourceArgs(

            ) {
    }
}
