// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example.inputs;

    public class PetArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Integer> age = java.util.Optional.empty();
        public Integer getAge() {
           return age.isPresent() ? age.get() : null;
        }
        public PetArgs setAge(Integer age) {
            this.age = age != null ? java.util.Optional.of(age) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.random.RandomPet> name = java.util.Optional.empty();
        public io.pulumi.random.RandomPet getName() {
           return name.isPresent() ? name.get() : null;
        }
        public PetArgs setName(io.pulumi.random.RandomPet name) {
            this.name = name != null ? java.util.Optional.of(name) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.List<io.pulumi.random.RandomPet>> nameArray = java.util.Optional.empty();
        public java.util.List<io.pulumi.random.RandomPet> getNameArray() {
           return nameArray.isPresent() ? nameArray.get() : null;
        }
        public PetArgs setNameArray(java.util.List<io.pulumi.random.RandomPet> nameArray) {
            this.nameArray = nameArray != null ? java.util.Optional.of(nameArray) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.Map<String, io.pulumi.random.RandomPet>> nameMap = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.random.RandomPet> getNameMap() {
           return nameMap.isPresent() ? nameMap.get() : null;
        }
        public PetArgs setNameMap(java.util.Map<String, io.pulumi.random.RandomPet> nameMap) {
            this.nameMap = nameMap != null ? java.util.Optional.of(nameMap) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<io.pulumi.random.RandomPet> requiredName = java.util.Optional.empty();
        public io.pulumi.random.RandomPet getRequiredName() {
           return requiredName.isPresent() ? requiredName.get() : null;
        }
        public PetArgs setRequiredName(io.pulumi.random.RandomPet requiredName) {
            this.requiredName = requiredName != null ? java.util.Optional.of(requiredName) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<java.util.List<io.pulumi.random.RandomPet>> requiredNameArray = java.util.Optional.empty();
        public java.util.List<io.pulumi.random.RandomPet> getRequiredNameArray() {
           return requiredNameArray.isPresent() ? requiredNameArray.get() : null;
        }
        public PetArgs setRequiredNameArray(java.util.List<io.pulumi.random.RandomPet> requiredNameArray) {
            this.requiredNameArray = requiredNameArray != null ? java.util.Optional.of(requiredNameArray) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<java.util.Map<String, io.pulumi.random.RandomPet>> requiredNameMap = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.random.RandomPet> getRequiredNameMap() {
           return requiredNameMap.isPresent() ? requiredNameMap.get() : null;
        }
        public PetArgs setRequiredNameMap(java.util.Map<String, io.pulumi.random.RandomPet> requiredNameMap) {
            this.requiredNameMap = requiredNameMap != null ? java.util.Optional.of(requiredNameMap) : java.util.Optional.empty();
            return this;
        }

        public PetArgs(
            io.pulumi.random.RandomPet requiredName,
            java.util.List<io.pulumi.random.RandomPet> requiredNameArray,
            java.util.Map<String, io.pulumi.random.RandomPet> requiredNameMap
            ) {
        this.requiredName = java.util.Optional.of(requiredName);
        this.requiredNameArray = java.util.Optional.of(requiredNameArray);
        this.requiredNameMap = java.util.Optional.of(requiredNameMap);
    }
}
