// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class ComponentArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<Boolean> a = java.util.Optional.empty();
        public Boolean getA() {
           return a.isPresent() ? a.get() : null;
        }
        public ComponentArgs setA(Boolean a) {
            this.a = a != null ? java.util.Optional.of(a) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Boolean> b = java.util.Optional.empty();
        public Boolean getB() {
           return b.isPresent() ? b.get() : null;
        }
        public ComponentArgs setB(Boolean b) {
            this.b = b != null ? java.util.Optional.of(b) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.example.inputs.Foo> bar = java.util.Optional.empty();
        public io.pulumi.example.inputs.Foo getBar() {
           return bar.isPresent() ? bar.get() : null;
        }
        public ComponentArgs setBar(io.pulumi.example.inputs.Foo bar) {
            this.bar = bar != null ? java.util.Optional.of(bar) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.List<io.pulumi.example.inputs.Foo>> baz = java.util.Optional.empty();
        public java.util.List<io.pulumi.example.inputs.Foo> getBaz() {
           return baz.isPresent() ? baz.get() : null;
        }
        public ComponentArgs setBaz(java.util.List<io.pulumi.example.inputs.Foo> baz) {
            this.baz = baz != null ? java.util.Optional.of(baz) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.Map<String, io.pulumi.example.inputs.Foo>> bazMap = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.example.inputs.Foo> getBazMap() {
           return bazMap.isPresent() ? bazMap.get() : null;
        }
        public ComponentArgs setBazMap(java.util.Map<String, io.pulumi.example.inputs.Foo> bazMap) {
            this.bazMap = bazMap != null ? java.util.Optional.of(bazMap) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<Integer> c = java.util.Optional.empty();
        public Integer getC() {
           return c.isPresent() ? c.get() : null;
        }
        public ComponentArgs setC(Integer c) {
            this.c = c != null ? java.util.Optional.of(c) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Integer> d = java.util.Optional.empty();
        public Integer getD() {
           return d.isPresent() ? d.get() : null;
        }
        public ComponentArgs setD(Integer d) {
            this.d = d != null ? java.util.Optional.of(d) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<String> e = java.util.Optional.empty();
        public String getE() {
           return e.isPresent() ? e.get() : null;
        }
        public ComponentArgs setE(String e) {
            this.e = e != null ? java.util.Optional.of(e) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<String> f = java.util.Optional.empty();
        public String getF() {
           return f.isPresent() ? f.get() : null;
        }
        public ComponentArgs setF(String f) {
            this.f = f != null ? java.util.Optional.of(f) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.example.inputs.FooArgs> foo = java.util.Optional.empty();
        public io.pulumi.example.inputs.FooArgs getFoo() {
           return foo.isPresent() ? foo.get() : null;
        }
        public ComponentArgs setFoo(io.pulumi.example.inputs.FooArgs foo) {
            this.foo = foo != null ? java.util.Optional.of(foo) : java.util.Optional.empty();
            return this;
        }

        public ComponentArgs(
            Boolean a,
            Integer c,
            String e
            ) {
        this.a = java.util.Optional.of(a);
        this.c = java.util.Optional.of(c);
        this.e = java.util.Optional.of(e);
    }
}
