// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;
public class Component extends io.pulumi.ComponentResource {
    public io.pulumi.Output<Boolean> a;
    public io.pulumi.Output<java.util.Optional<Boolean>> b;
    public io.pulumi.Output<java.util.Optional<io.pulumi.example.outputs.Foo>> bar;
    public io.pulumi.Output<java.util.Optional<java.util.List<io.pulumi.example.outputs.Foo>>> baz;
    public io.pulumi.Output<Integer> c;
    public io.pulumi.Output<java.util.Optional<Integer>> d;
    public io.pulumi.Output<String> e;
    public io.pulumi.Output<java.util.Optional<String>> f;
    public io.pulumi.Output<java.util.Optional<io.pulumi.example.outputs.Foo>> foo;

    /**    * Create a Component resource with the given name, arguments, and options.
    * @param name the unique name of the resource
    * @param args The arguments used to populate this resource's properties
    * @param options A bag of options that control this resource's behavior
    */
    public Component(String name, ComponentArgs args, @javax.annotation.Nullable io.pulumi.ComponentResourceOptions options) {
        super("example::Component", name, args, makeResourceOptions(options, io.pulumi.Input.create("")), true);
    }

    private static io.pulumi.ComponentResourceOptions makeResourceOptions(@javax.annotation.Nullable io.pulumi.ComponentResourceOptions options, io.pulumi.Input<String> id) {
        io.pulumi.ComponentResourceOptions defaultOptions = new io.pulumi.ComponentResourceOptions();
        defaultOptions.Version = Utilities.Version;
        io.pulumi.ComponentResourceOptions merged = io.pulumi.ComponentResourceOptions.merge(defaultOptions, options);
        merged.Id = id;
        return merged;
    }
}
