// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;
public class ArgFunction {
    public static java.util.concurent.CompletableFuture<ArgFunctionResult> invokeAsync(@javax.annotation.Nullable ArgFunctionArgs args, InvokeOptions options) {
        return io.pulumi.Deployment.Instance.<ArgFunctionResult>invokeAsync("example::argFunction", args != null ? args : new ArgFunctionArgs(), options.WithVersion());
    }
}
