// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class CatArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<Integer> age = java.util.Optional.empty();
        public Integer getAge() {
           return age.isPresent() ? age.get() : null;
        }
        public CatArgs setAge(Integer age) {
            this.age = age != null ? java.util.Optional.of(age) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.example.inputs.PetArgs> pet = java.util.Optional.empty();
        public io.pulumi.example.inputs.PetArgs getPet() {
           return pet.isPresent() ? pet.get() : null;
        }
        public CatArgs setPet(io.pulumi.example.inputs.PetArgs pet) {
            this.pet = pet != null ? java.util.Optional.of(pet) : java.util.Optional.empty();
            return this;
        }

        public CatArgs(

            ) {
    }
}
