// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class ComponentArgs extends io.pulumi.ResourceArgs {
        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> metadata = java.util.Optional.empty();
        public io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs getMetadata() {
           return metadata.isPresent() ? metadata.get() : null;
        }
        public ComponentArgs setMetadata(io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs metadata) {
            this.metadata = metadata != null ? java.util.Optional.of(metadata) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs>> metadataArray = java.util.Optional.empty();
        public java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> getMetadataArray() {
           return metadataArray.isPresent() ? metadataArray.get() : null;
        }
        public ComponentArgs setMetadataArray(java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> metadataArray) {
            this.metadataArray = metadataArray != null ? java.util.Optional.of(metadataArray) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = false)
        private java.util.Optional<java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs>> metadataMap = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> getMetadataMap() {
           return metadataMap.isPresent() ? metadataMap.get() : null;
        }
        public ComponentArgs setMetadataMap(java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> metadataMap) {
            this.metadataMap = metadataMap != null ? java.util.Optional.of(metadataMap) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> requiredMetadata = java.util.Optional.empty();
        public io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs getRequiredMetadata() {
           return requiredMetadata.isPresent() ? requiredMetadata.get() : null;
        }
        public ComponentArgs setRequiredMetadata(io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs requiredMetadata) {
            this.requiredMetadata = requiredMetadata != null ? java.util.Optional.of(requiredMetadata) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs>> requiredMetadataArray = java.util.Optional.empty();
        public java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> getRequiredMetadataArray() {
           return requiredMetadataArray.isPresent() ? requiredMetadataArray.get() : null;
        }
        public ComponentArgs setRequiredMetadataArray(java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> requiredMetadataArray) {
            this.requiredMetadataArray = requiredMetadataArray != null ? java.util.Optional.of(requiredMetadataArray) : java.util.Optional.empty();
            return this;
        }

        @io.pulumi.serialization.InputAttribute(isRequired = true)
        private java.util.Optional<java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs>> requiredMetadataMap = java.util.Optional.empty();
        public java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> getRequiredMetadataMap() {
           return requiredMetadataMap.isPresent() ? requiredMetadataMap.get() : null;
        }
        public ComponentArgs setRequiredMetadataMap(java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> requiredMetadataMap) {
            this.requiredMetadataMap = requiredMetadataMap != null ? java.util.Optional.of(requiredMetadataMap) : java.util.Optional.empty();
            return this;
        }

        public ComponentArgs(
            io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs requiredMetadata,
            java.util.List<io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> requiredMetadataArray,
            java.util.Map<String, io.pulumi.kubernetes.meta/v1.inputs.ObjectMetaArgs> requiredMetadataMap
            ) {
        this.requiredMetadata = java.util.Optional.of(requiredMetadata);
        this.requiredMetadataArray = java.util.Optional.of(requiredMetadataArray);
        this.requiredMetadataMap = java.util.Optional.of(requiredMetadataMap);
    }
}
