// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class ProviderArgs extends io.pulumi.ResourceArgs {
        public ProviderArgs(

            ) {
    }
}
