// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.pulumi.example;

    public class WorkloadArgs extends io.pulumi.ResourceArgs {
        public WorkloadArgs(

            ) {
    }
}
